### ISSUE TITLE
[Scopes] Tracking issue for original scope mapping tasks

### ISSUE THREAD

**Issue by loganfsmyth** [firefox-devtools/debugger#6400]
This is a general tracking issue, which replaces #5561 and starts fresh with our current goals.

#### Bugs

* [x] Handle function body scope with lex and nonlex decls #6387
* [x] Ensure that regenerator maps `yield` statements to `return` statements [regenerator issue #342](https://github.com/facebook/regenerator/issues/342) [regenerator PR #344]( https://github.com/facebook/regenerator/pull/344) :runner: 
* [x] Use the original file ranges to more effectively exclude whole-line mappings #6405
* [x] Multiple classes in the same module (Wheel demo)
* [x] `cycleItems` is no longer mapped #6564
* [x] Flow `import { type Foo } from` bindings are included incorrectly #6655
* [x] Flow/TS binding references should be entirely skipped in scope analysis #6655
* [x] Fix bindings incorrectly marked `(optimized out)` #6710 (From code introduced in #6674)
* [x] `this` in the debugger
* [x] create react app source mappings

#### Features 

* [ ] Include original binding data in console autocomplete
* [ ] Verify/add support for "sections" in sourcemaps
* [ ] Handle complex expression mappings better
  * [x] Expose server APIs for calling functions and getters [devtools server PR](https://bugzilla.mozilla.org/show_bug.cgi?id=1473996)
  * [ ]  We should execute module namespace getters to show the real value. Modules generally use getters for live values, rather than side-effects, so it should be within user expectations to trigger those
  * [ ] Some module imports are mapped to function calls instead of property accesses, but we cannot currently call these functions to get their values

#### `source-map`

* [ ] Enhance `applySourceMap` to use range matching instead of closest-matching
* [ ] Expose both relative and absolute paths to allow more easily passing sources from consumers to generators
* [ ] Return additional contexual data from results of `generatedPositionFor` and `originalPositionFor` at least, so users know where they `bias` value took them
* [ ] Consider exposing an async-initialization API for `source-map` that would allow for synchronous consumption once initialized
* [ ] Implement official type definitions for the library
* [ ] Explore if there are internal validation changes that can be made to ensure mappings are valid (line/column always positive, for example)

#### `babel`/`typescript`

* [ ] Explore defining clear rules of _how_ syntax is mapped.
  * Are mappings per-token? 
  * Expressions are complex nested structures, but maps can only represent flat ranges, so what are the expectations there?
  * What are the expectations for whitespace? 
  * How should stepping to the very end of a function be mapped?

#### `babel`

* [ ] Explore improvements that can be made to Babel
* [ ] Turns out Babel's `t.isReferenced` (used in the parser worker's visitor.js) isn't great
  * `[ foo ] = []` does not recognize `foo` as a reference
  * `foo = 42` is not recognized either
  * `{ prop: foo } = {}` _is_ because it is an object property, even if it is inside a pattern

#### Spider Monkey

* [x] Add Debugger.Script.isModule [PR](https://bugzilla.mozilla.org/show_bug.cgi?id=1468384)
* [x] Column Breakpoints should be available for member expression [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1378808)
* [x]  Rationalize how BytecodeEmitter generates column-number source notes [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1436407) 
  * [x] Split into separate, less ambitious task [PR](https://bugzilla.mozilla.org/show_bug.cgi?id=1472291)
* [ ] Debugger.Environment.prototype.type should return more detailed information [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1414683)

#### Ecosystem

* [ ] Expand testcases for other bundling/sourcemap generation tooling
  * [x] Refactor system to allow test fixtures to be used across build tools: #6701
  * [x] Webpack
  * [x] Rollup - #6674 -  [Babel improvements to help Rollup](https://github.com/babel/babel/pull/8380)
  * [ ] Browserify
  * [x] Parcel
  * [ ] Explore how we handle minified code
* [ ] Explore non-Babel implementations of imports to see if mappings need improvements
* [x] Create more testcases around Babel's binding mappings for various complex transformations

**Comment by jasonLaster** [comment]
### Multiple classes in the same module

STR: 
1. git clone https://github.com/jasonLaster/hams
2. yarn ; yarn start
3. pause in wheel/index.js Circle#render



when the mappings do work, it looks like `cName` might be mapped poorly too.
<img src='https://shipusercontent.com/2a089106d808e66f037769bd32b3bbfc/Screen%20Shot%202018-06-01%20at%207.43.38%20AM.png' title='Screen Shot 2018-06-01 at 7.43.38 AM.png' width=1552>

**Comment by jasonLaster** [comment]
STR:
1. go to https://dbg-class-prop-this.glitch.me/
2. add a breakpoint in HelloWorld#onSortClick

<img src='https://shipusercontent.com/312f1c4c873b2e1c0cfeaa28df8d97e3/Screen%20Shot%202018-06-01%20at%208.46.34%20AM.png' title='Screen Shot 2018-06-01 at 8.46.34 AM.png' width=1552>

**Comment by jasonLaster** [comment]
This is optimized out

STR: 

1. add a breakpoint in SourceTreeItem.js#renderItemName
2. reload a page

![screen shot 2018-08-07 at 5 30 24 pm](https://user-images.githubusercontent.com/254562/43803740-a58c0af0-9a67-11e8-8655-90fe466f46d0.png)
![screen shot 2018-08-07 at 5 30 21 pm](https://user-images.githubusercontent.com/254562/43803741-a59df152-9a67-11e8-86ee-8ffdc3d3ac1a.png)

**Comment by jasonLaster** [comment]
Looks like create react app is having some issues with the mappings:
https://github.com/devtools-html/debugger.html/issues/6762
