### ISSUE TITLE
[Pretty Print] Modern JS

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#6591]
Pretty Fast does a poor job of understanding some modern JS and as a result creates bad pretty print locations

#### bugs

- [ ] Instant crash on prettify on ravelry.com #5894 🥇
- [x] [Pause] debugger doesn’t show the pause state #5951
- [x] [Breakpoints] After setting a breakpoint, debugger refuses to step through the code #5807

**Comment by nmicht** [comment]
@jasonLaster I think we should close this one.
The remaining work is to improve the performance for the pretty print as mentioned on #5894

**Comment by jasonLaster** [comment]
Thanks @nmicht
