### ISSUE TITLE
[PrettyPrint] Improve location quality

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#6592]
There are a couple of issues with how we handle locations when prettyprinting

- [x] pauses without a bp on load #5519 #5827 🥇
- [x] jsx sets a breakpoint on the line above #6685
- [ ] selectLocation to do less work with regard to pretty print #5618 
- [ ] prettifying should remember the user intent to jump to a specific line #3778 
- [ ] breakpoints are not persisted #3532

**Comment by janodvarko** [comment]
Most of the bugs are closed (except of #5618)

Closing

Honza
