### ISSUE TITLE
[Tracking] Column Breakpoints 

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7241]
Supersedes #7028.

[Server-side Meta Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1528417).

Column breakpoints are currently flagged as `devtools.debugger.features.column-breakpoints`.  Once we turn them on, there are a number of tasks remaining:

## MVP
- [x] Update the marker logic to only display if the column breakpoint location is within the viewport.
- [x] Performance: Switching between tabs is painfully slow when column breakpoints are enabled.
- [x] Disable column breakpoints for pretty printed files and original sources with line breakpoints (https://github.com/devtools-html/debugger.html/issues/7248)

## Polish
- [x] When clicking on the line in the gutter to add a breakpoint, add the breakpoint to the first possible column, not just `0` or `undefined` (*Status*: PR:  https://github.com/devtools-html/debugger.html/pull/7392)
- [x] Ensure that the breakpoint symbol on the editor line isn't removed when a column breakpoint is deactivated, unless the only activated column breakpoint is removed.  (*Status*: PR:  https://github.com/devtools-html/debugger.html/pull/7410)
- [x] Add a context menu to column breakpoints   (*Status*: Experiment:  https://github.com/darkwing/debugger.html/tree/experiment-column-context)
- [x] Ensure that jumping to a pause location still scrolls to the right location.  (*Status*: None) 
- [x] Implement new UI
- [x] Memoize getCallSites (*Status*: None; *Bug:* https://github.com/devtools-html/debugger.html/issues/7309)
- [x] Enrich the gutter and breakpoint menus to include "Disable all on line", "Enable all on line", "Remove all on line" (*Status*: None)

## Todos

- [x] add server integration for breakable positions
- [x] Review how breakpoint sync behaves as files with column breakpoints change to make sure that still works well
- [x] should be able to preview
- [x]  enable column breakpoints for the tests
- [x]  enable column breakpoints
- [x] update selected location support #8025 
- [x] load breakpoint positions when a source is loaded
- [x] finish column bps test [pr]
- [x] review [Critical Path Interactions][cpi]
- [x] Resolve onSources exception: #8106
- [ ] Breakpoints in HTML files with more than one `<script>` are broken: [bugzilla 1535246](https://bugzilla.mozilla.org/show_bug.cgi?id=1535246)

### Polish
- [x] Generated breakpoint position does not correspond with original [Bugzilla #1533571](https://bugzilla.mozilla.org/show_bug.cgi?id=1533571)
- [ ] Unexpectedly getting the _second_ breakpoint enabled on line #8092 
- [x] Column breakpoints seem to spring into existance when you stop scrolling #8089
- [x] Can't add a breakpoint in increment bundle.js:106:51
- [x] Implement new colors #7332 
- [x] Shift-clicking line-breakpoint does not toggle *all* enabled column breakpoints #8105

[pr]: https://github.com/devtools-html/debugger.html/pull/7752

[cpi]: https://docs.google.com/document/d/1IqkVX_4MAMkJy6gRe8OHfB4vYqzdps8VwIEThIzrEKU/edit#heading=h.1ukwpv9fyebv

**Comment by jasonLaster** [comment]
@darkwing i think the preview thing might have been fixed :)

**Comment by digitarald** [comment]
Checked off *Critical Path Interactions* and found one bug.
