### ISSUE TITLE
[Tracking] Breakpoints

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7493]
This will track bug fixes and improvements to our breakpoint handling.

- [x] breakpoints do not appear in gutter on open (https://github.com/devtools-html/debugger.html/issues/7289)
- [ ] Breakpoint doesn't survive any attempts at reloading the page (https://github.com/devtools-html/debugger.html/issues/7260)
- [ ] Column Breakpoints gets Added to next line (https://github.com/devtools-html/debugger.html/issues/7166)
- [ ] Debugger can't set breakpoint (https://github.com/devtools-html/debugger.html/issues/6965)
- [ ] Break at wrong location (https://github.com/devtools-html/debugger.html/issues/6873)
- [ ] Use `loading` property (https://github.com/devtools-html/debugger.html/issues/6771)
- [x] Page load breakpoint pausing performance audit (https://github.com/devtools-html/debugger.html/issues/6754)
- [ ] Breakpoint changes its place on page refresh (https://github.com/devtools-html/debugger.html/issues/6580)
- [ ] The debugger breaks at unexpected places when addons inject code (https://github.com/devtools-html/debugger.html/issues/5817)
- [ ] Breakpoints slide to a different line (https://github.com/devtools-html/debugger.html/issues/7501)

**Comment by digitarald** [comment]
@darkwing it seems to me that some of these can be duped with column breakpoints and or the server-side breakpoint work by @loganfsmyth ?

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
