### ISSUE TITLE
Multi-target worker debugging

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7552]
It would be great to support multi-target debugging from within devtools

### check list

- [x] redux architecture should support workers #7525 
- [ ] see worker sources in the source tree
- [ ] breakpoints pane (see each worker source breakpoint)
- [ ] tabs (see each worker source)
- [ ] clean up selected thread UI
- [ ] stepping support with workers
- [ ] sourcemap support
