### ISSUE TITLE
UI Quality

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7677]
There are a number of small to medium sized improvements we should fix in the debugger UI over the next version of Firefox:

## Primary Pane (Sources Tree & Outline View)

- [x] Non-existing directory root causes to empty sources tree #7658
- [x] [sources] Workers break the directory root layout #7656
- [x] Use the same expand arrow icon as Inspector, Console etc. #7566
- [ ] [sources] Set directory root does not work for debugger.html #7571

## Editor (Tabs, Editor, Search )

- [x] The "Evaluate in console" context menu item does not work #7668
- [x] [Editor] The cursor location should be to the left of the toggle button #7666
- [x] Gutter line number colors #7647
- [x] Search field polish #7425
- [ ] [QuickOpenModal] Bold font of highlighted <mark>'s are blurry on Windows #7490
- [ ] Navigating callstack conflicts with search result focussing #6747
- [x] Default icon color should use --theme-toolbar-icon-color #7743
- [x] Left "Collapse panes" button icon is blurry #7742
- [ ] Occasionally the debug line is not cleared #7755
- [x] highlight line flashes when it is scrolled into view #7757

## Secondary Pane (Watch Expressions, Breakpoints, Scopes)
- [x] [SecondaryPane] The command bar should be visible when the panel is collapsed #7667
- [x] Two Breakpoints Active in Secondary Pane #6734

## Context Menus

- [x] In breakpoints context menu: Missing `+` in shortcuts #7652
- [x] Restructure Context Menus #7497
- [x] Tab Context Menu Doesn't Take Into Account Pretty URLs #7473
- [ ] Context menu Source actions should be available from the SourcePanel and Source Tab #7287
- [x] Breakpoints Panel Context Menu Using Wrong Breakpoint #7737

## Performance
- [x] memoize highlightText  #7772 
- [x] memoize getURL by ID #7771
- [ ] Severe main thread hangs w/ glitch+debugger open in background #7780
- [ ] General debugger slowness on a large(ish) project #7734

**Comment by darkwing** [comment]
Incredible effort by everyone involved in this first quality sprint!  I'm blown away!  

Closing this issue and moving remaining items to sprint 2!
