### ISSUE TITLE
[tracking] Worker Debugging

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7710]
Server-side meta bug: [1520698](https://bugzilla.mozilla.org/show_bug.cgi?id=1520698).

#### Todos
- [x] refreshing clears selected source #7708 
- [ ] [Workers] Use one tree instead of one tree per thread #8005 
- [x] remove sources when a worker is removed #7660

**Comment by jasonLaster** [comment]
With the second bug, i was able to "fix" the problem by flagging off workers in the client and changing isWorker

```diff
diff --git a/devtools/client/debugger/new/src/client/firefox/commands.js b/devtools/client/debugger/new/src/client/firefox/commands.js
index 9633efd63d94..c050403c25cf 100644
--- a/devtools/client/debugger/new/src/client/firefox/commands.js
+++ b/devtools/client/debugger/new/src/client/firefox/commands.js
@@ -417,7 +417,7 @@ async function fetchSources(): Promise<any[]> {
 }

 async function fetchWorkers(): Promise<Worker[]> {
-  if (features.windowlessWorkers) {
+  if (false && features.windowlessWorkers) {
     workerClients = await updateWorkerClients({
       tabTarget,
       debuggerClient,
diff --git a/devtools/client/debugger/new/src/utils/workers.js b/devtools/client/debugger/new/src/utils/workers.js
index b31801bc9085..60f0d90e5c0f 100644
--- a/devtools/client/debugger/new/src/utils/workers.js
+++ b/devtools/client/debugger/new/src/utils/workers.js
@@ -12,5 +12,5 @@ export function getDisplayName(thread: Thread) {
 }

 export function isWorker(thread: Thread) {
-  return thread.actor.includes("workerTarget");
+  return false; // thread.actor.includes("workerTarget");
 }
```

**Comment by jasonLaster** [comment]
@WenInCode i think `dbg.features.windowlessDebuggers` has to be true for it to regress

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
