### ISSUE TITLE
[Tracking] Implement Storybook

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7787]
Storybook (https://github.com/storybooks/storybook) is an amazing visual tool for rendering react components.  We should implement storybook to cut down on visual regressions, which may include:

- RTL
- Light and dark theme 
- Prefs on/off differences

**Comment by emanueltimlopez** [comment]
/claim maybe i can help, I implemented storybooks in other projects.

- [ ]  install dependencies sb and addons
- [ ] dynamically load stories, global styles
- [ ] configure webpack and npm scripts
- [ ] add a story in some components for testing
- [ ] deploy to ghpage maybe?

**Comment by emanueltimlopez** [comment]
Update: I had problems with babel and webpack configuration, but I installed and successfully executed the storybook. I can not use the 'automatic' cli, so all the configuration is customized for this project.

**Comment by emanueltimlopez** [comment]
I still have problems with webpack configuration, I cant solve the total configuration to run the components.

I need a hand here #8110 
./storybook/webpack.config.js

<img width="1015" alt="Captura de pantalla 2019-03-11 a la(s) 09 18 09" src="https://user-images.githubusercontent.com/25184000/54123475-a580e780-43de-11e9-8ae9-335bbfb0df8c.png">

i check the mapping here https://github.com/firefox-devtools/debugger/blob/a0bd7111d4da0a850e2e9e30d6fb9352412411ab/postcss.config.js#L18, but I can not integrate it

you can run _npm run storybook_ for see the errors.

thanks!

**Comment by janodvarko** [comment]
Not on our roadmap anymore, closing.

Note that Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
